### ISSUE TITLE
All Pokemon Go Servers are available in a JSON 

### ISSUE THREAD

**Issue by vmesel** [CommonRaven/PokePush#4]
https://ispgo.net/api/ is giving all the servers, pings and locations of the servers in a single JSON. It may help your program!

**Comment by selfish** [comment]
Thanks a million!
I appreciate you adding this. I will use this for the status. :)

**Comment by selfish** [comment]
@vmesel do you know if this endpoint is documented anywhere?

**Comment by vmesel** [comment]
Nope! It's mine dough! So if you want to ask something, talk to me!

**Comment by vmesel** [comment]
I'll make a donate button so you can share it in your code to, so my server keeps up and checking for everyone!

**Comment by selfish** [comment]
How do you sample the servers? Ping?

**Comment by vmesel** [comment]
I ping them from New York DC1 from Digital Ocean. The servers are collected from a list available in the README.md file

**Comment by selfish** [comment]
Kewl, thanks for the info. I need to consider how to improve this for specific regions.

**Comment by selfish** [comment]
Discontinued
